### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by leocaseiro** [tutsplus/easier-javascript-apps-with-angularjs#1]
It seems there're some files missing as contact.js, list.html and so on listed on the video: https://code.tutsplus.com/courses/easier-javascript-apps-with-angularjs/lessons/routing-primer

**Comment by adamarthurryan** [comment]
Thanks, I'm contacting the instructor to look into the missing files.

**Comment by adamarthurryan** [comment]
@leocaseiro - Sorry, I haven't been able to reach the instructor to find the missing source files. I'll make a note in the course readme, warning other users that there are missing files. In the meantime, we have some more recent AngularJS content available that may be of interest to you:
https://code.tutsplus.com/categories/angularjs/courses
